### ISSUE TITLE
offer detail returns languageLevel for unused languages

### ISSUE THREAD

**Issue by stefanides** [IWSDevelopers/iws#18]
offer detail in fetchOffer() returns languageLevel also for first unused language = such data are not consistent and have to be fixed on client side. check e.g. 
>    ["offerId":protected]=>
    string(36) "c5f98a58-2928-493c-9251-3b8cc6996dab"
    ["refNo":protected]=>
    string(15) "IN-2016-3430-MU"
....
   ["language1":protected]=>
    string(7) "ENGLISH"
    ["language1Level":protected]=>
    string(1) "E"
    ["language1Operator":protected]=>
    string(1) "A"
    ["language2":protected]=>
    NULL
    ["language2Level":protected]=>
    string(1) "E"
    ["language2Operator":protected]=>
    NULL
    ["language3":protected]=>
    NULL
    ["language3Level":protected]=>
    NULL

where the language2 is null, but language2Level requires that null to have 'excellent' level. The 3rd language is already Ok.

**Comment by knjensen** [comment]
Bug report is legit, will correct it as part of the first IWS 1.2.0 release.

**Comment by knjensen** [comment]
The last commit has resolved this issue.
